# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170321_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='characterimage',
            new_name='character_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profileimage',
            new_name='profile_image',
        ),
    ]
