# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170321_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='First Name', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=15),
        ),
    ]
