# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170321_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nickname',
        ),
    ]
