# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_member_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
