# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
